export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST"
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS"
export const ADD_COMMENT_FAILED  = "ADD_COMMENT_FAILED"


export const GET_COMMENT_REQUEST = "GET_COMMENT_REQUEST"
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS"
export const GET_COMMENT_FAILED  = "GET_COMMENT_FAILED"


export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST"
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS"
export const DELETE_COMMENT_FAILED  = "DELETE_COMMENT_FAILED"


export const DELETE_ADMIN_COMMENT_REQUEST = "DELETE_ADMIN_COMMENT_REQUEST"
export const DELETE_ADMIN_COMMENT_SUCCESS = "DELETE_ADMIN_COMMENT_REQUEST"
export const DELETE_ADMIN_COMMENT_FAILED  = "DELETE_ADMIN_COMMENT_REQUEST"