export const ADD_POST_REQUEST = "ADD_POST_REQUEST"
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS"
export const ADD_POST_FAILED  = "ADD_POST_FAILED"


export const GET_POST_REQUEST = "GET_POST_REQUEST"
export const GET_POST_SUCCESS = "GET_POST_SUCCESS"
export const GET_POST_FAILED  = "GET_POST_FAILED"


export const GET_MY_POST_REQUEST = "GET_MY_POST_REQUEST"
export const GET_MY_POST_SUCCESS = "GET_MY_POST_SUCCESS"
export const GET_MY_POST_FAILED  = "GET_MY_POST_FAILED"


export const UPDATE_MY_POST_REQUEST = "UPDATE_MY_POST_REQUEST"
export const UPDATE_MY_POST_SUCCESS = "UPDATE_MY_POST_SUCCESS"
export const UPDATE_MY_POST_FAILED  = "UPDATE_MY_POST_FAILED"


export const DELETE_MY_POST_REQUEST = "DELETE_MY_POST_REQUEST"
export const DELETE_MY_POST_SUCCESS = "DELETE_POST_SUCCESS"
export const DELETE_MY_POST_FAILED  = "DELETE_POST_FAILED"


export const GET_POST_COUNT_REQUEST = "GET_POST_COUNT_REQUEST"
export const GET_POST_COUNT_SUCCESS = "GET_POST_COUNT_SUCCESS"
export const GET_POST_COUNT_FAILED  = "GET_POST_COUNT_FAILED"


export const LOADING = "LOADING"


export const SUCCESS = "SUCCESS"


export const FAILED =  "FAILED"


export const DELETE_ADMIN_POST_REQUEST = "DELETE_ADMIN_POST_REQUEST"
export const DELETE_ADMIN_POST_SUCCESS = "DELETE_ADMIN_POST_SUCCESS"
export const DELETE_ADMIN_POST_FAILED  = "DELETE_ADMIN_POST_FAILED"


