export const ADD_SOLUTION_REQUEST = "ADD_SOLUTION_REQUEST"
export const ADD_SOLUTION_SUCCESS = "ADD_SOLUTION_SUCCESS"
export const ADD_SOLUTION_FAILED  = "ADD_SOLUTION_FAILED"


export const GET_SOLUTION_REQUEST = "GET_SOLUTION_REQUEST"
export const GET_SOLUTION_SUCCESS = "GET_SOLUTION_SUCCESS"
export const GET_SOLUTION_FAILED  = "GET_SOLUTION_FAILED"


export const DELETE_SOLUTION_REQUEST = "DELETE_SOLUTION_REQUEST"
export const DELETE_SOLUTION_SUCCESS = "DELETE_SOLUTION_SUCCESS"
export const DELETE_SOLUTION_FAILED  = "DELETE_SOLUTION_FAILED"


export const LOADING = "LOADING"


export const SUCCESS = "SUCCESS"


export const FAILED =  "FAILED"